#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(
    cd "$(dirname "${BASH_SOURCE[0]}")"
    pwd -P
)"

if ! "$SCRIPT_DIR/../scripts/lint-and-prettify.sh" --dry-run; then
    echo "ERROR: Lint failure." >&2
    exit 1
else
    echo "SUCCESS: Lint passed."
fi
